### ISSUE TITLE
Request for Datasets Used in Smart-Berth-Planning

### ISSUE THREAD

**Issue by Rendrick27** [afonsomm/Smart-Berth-Planning#1]
Hello afonsomm

I hope you are doing well. I'm contacting you to inquire about the possibility of having the datasets utilized in your project publicly available (Example: nari_dynamic.csv and others).

Best regards,
Rendrick

**Comment by afonsomm** [comment]
Hi @Rendrick27. Shared a zip file with the data (check your email).

**Comment by Rendrick27** [comment]
Hello there

Thanks for sharing the data @afonsomm ^^

Best regards
